;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   jue oct 16 2025
; Processor: PIC16F887
; Compiler:  MPASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

LIST P=16F887
#include p16f887.inc                ; Include register definition file

;====================================================================
; Configuracion General
;====================================================================
   __CONFIG _CONFIG1, _XT_OSC & _WDTE_OFF & _MCLRE_ON & _LVP_OFF
   __CONFIG _CONFIG2, _WRT_OFF
;====================================================================
; VARIABLES
;====================================================================
   CBLOCK 0x20
      W_TEMP
      STATUS_TEMP
      N_TECLA
      DSPL
      ; Variables para buffer de display
      DISPLAY_BUFFER_1
      DISPLAY_BUFFER_2
      DISPLAY_BUFFER_3
      DISPLAY_BUFFER_4
      BUFFER_INDEX
      CURRENT_DIGIT
      DIGIT_COUNTER
   ENDC
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      ORG   0x00
      goto  INICIO
      ORG 0x04
      goto ISR_INICIO
      ORG 0x05      
;====================================================================
; DEFINICION DE MACROS
;====================================================================
   CFG_BTN	MACRO
   BANKSEL ANSELH
   CLRF ANSELH
   BANKSEL TRISB
   MOVLW B'00111000'  
   MOVWF TRISB
   BANKSEL OPTION_REG
   BCF OPTION_REG, NOT_RBPU
   BANKSEL WPUB
   MOVLW B'00111000'
   MOVWF WPUB
   BANKSEL PORTB
   MOVLW B'01000000'
   MOVWF PORTB
ENDM

   CFG_DISPLAY	MACRO
   BANKSEL TRISD
   CLRF TRISD
   BANKSEL PORTD
   CLRF PORTD
   ; Configurar pines de seleccion de display (PORTA o PORTC)
   BANKSEL TRISA
   MOVLW B'11110000'  ; RA0-RA3 para seleccion de displays
   MOVWF TRISA
   BANKSEL PORTA
   MOVLW B'00000000'
   MOVWF PORTA
ENDM

   CFG_ISR	MACRO
   BANKSEL INTCON 
   MOVLW B'10001000'
   MOVWF INTCON
   BANKSEL IOCB
   MOVLW B'00111000'
   MOVWF IOCB


ENDM


;====================================================================
; CODE SEGMENT
;====================================================================

INICIO	CFG_BTN
	CFG_DISPLAY
	CFG_ISR
    ; Inicializar variables de display
    MOVLW 0xC0  ; '0' en display vacio
    MOVWF DISPLAY_BUFFER_1
    MOVWF DISPLAY_BUFFER_2
    MOVWF DISPLAY_BUFFER_3
    MOVWF DISPLAY_BUFFER_4
    MOVLW D'0'
    MOVWF BUFFER_INDEX
    MOVLW D'1'
    MOVWF CURRENT_DIGIT
    MOVLW D'0'
    MOVWF DIGIT_COUNTER
    GOTO MAIN_LOOP

    MAIN_LOOP
    CALL MULTIPLEX_DISPLAYS
    GOTO MAIN_LOOP

    TABLE_DSPL
    ADDWF PCL
    ; TABLA PARA DISPLAY ANODO COMUN (0 = segmento encendido)
    RETLW 0xC0  ; 0
    RETLW 0xF9  ; 1
    RETLW 0xA4  ; 2
    RETLW 0xB0  ; 3
    RETLW 0x99  ; 4
    RETLW 0x92  ; 5
    RETLW 0x82  ; 6
    RETLW 0xF8  ; 7
    RETLW 0x80  ; 8
    RETLW 0x90  ; 9
    RETLW 0x88  ; A
    RETLW 0x83  ; b
    RETLW 0xC6  ; C
    RETLW 0xA1  ; d
    RETLW 0x86  ; E
    RETLW 0x8E  ; F
    RETLW 0xFF  ; Display vacio (todos apagados)

    ;====================================================================
    ; RUTINA DE MULTIPLEXACION DE DISPLAYS
    ;====================================================================
    MULTIPLEX_DISPLAYS
    ; Apagar todos los displays primero
    BANKSEL PORTA
    MOVLW B'11110000'
    MOVWF PORTA

    ; Seleccionar display actual
    MOVF CURRENT_DIGIT,W
    ANDLW 0x03
    BTFSC STATUS,Z
    GOTO SELECT_DISPLAY_1
    MOVLW D'1'
    SUBWF CURRENT_DIGIT,W
    BTFSC STATUS,Z
    GOTO SELECT_DISPLAY_2
    MOVLW D'2'
    SUBWF CURRENT_DIGIT,W
    BTFSC STATUS,Z
    GOTO SELECT_DISPLAY_3
    GOTO SELECT_DISPLAY_4

    SELECT_DISPLAY_1
    BANKSEL PORTA
    BCF PORTA,RA0
    MOVLW DISPLAY_BUFFER_1
    GOTO DISPLAY_DIGIT

    SELECT_DISPLAY_2
    BANKSEL PORTA
    BCF PORTA,RA1
    MOVLW DISPLAY_BUFFER_2
    GOTO DISPLAY_DIGIT

    SELECT_DISPLAY_3
    BANKSEL PORTA
    BCF PORTA,RA2
    MOVLW DISPLAY_BUFFER_3
    GOTO DISPLAY_DIGIT

    SELECT_DISPLAY_4
    BANKSEL PORTA
    BCF PORTA,RA3
    MOVLW DISPLAY_BUFFER_4

    DISPLAY_DIGIT
    MOVWF FSR
    MOVF INDF,W
    CALL TABLE_DSPL
    BANKSEL PORTD
    MOVWF PORTD

    ; Delay de 50ms para pruebas
    CALL DELAY_50MS

    ; Cambiar al siguiente display
    INCF CURRENT_DIGIT,F
    MOVF CURRENT_DIGIT,W
    SUBLW D'4'
    BTFSC STATUS,Z
    CLRF CURRENT_DIGIT

    RETURN

    ;====================================================================
    ; RUTINAS DE DELAY
    ;====================================================================
    DELAY_50MS
    ; Aproximadamente 50ms @ 4MHz
    MOVLW D'50'
    MOVWF DIGIT_COUNTER
    DELAY_LOOP_50MS_OUTER
    MOVLW D'250'
    MOVWF DIGIT_COUNTER
    DELAY_LOOP_50MS_INNER
    NOP
    NOP
    DECFSZ DIGIT_COUNTER,F
    GOTO DELAY_LOOP_50MS_INNER
    DECFSZ DIGIT_COUNTER,F
    GOTO DELAY_LOOP_50MS_OUTER
    RETURN

    ISR_INICIO
    ; GUARDADO DE CONTEXTO
    MOVWF W_TEMP
    SWAPF STATUS,W
    MOVWF STATUS_TEMP
    GOTO ISR_TECL

    ISR_TECL
    CALL TECL_PRESS
    GOTO TECL_LOAD

    TECL_PRESS
    MOVLW D'0'
    MOVWF N_TECLA
    ; Primero configurar columnas como salida y filas como entrada
    MOVLW B'01000000'  ; RB6 como salida (columna 1), RB3-5 como entrada (filas)
    MOVWF PORTB
    NOP
    CALL CHECK_ROW_RB3
    CALL CHECK_ROW_RB4
    CALL CHECK_ROW_RB5

    ; Segunda columna
    MOVLW B'10000000'  ; RB7 como salida (columna 2), RB3-5 como entrada (filas)
    MOVWF PORTB
    NOP
    CALL CHECK_ROW_RB3_2
    CALL CHECK_ROW_RB4_2
    CALL CHECK_ROW_RB5_2

    CALL TECL_RST

    CHECK_ROW_RB3
    BTFSS PORTB, RB3  ; Si RB3 = 0, tecla presionada
    RETURN
    MOVLW D'1'
    MOVWF N_TECLA     ; Tecla 1 detectada
    CALL TECL_DELAY
    RETURN

    CHECK_ROW_RB4
    BTFSS PORTB, RB4  ; Si RB4 = 0, tecla presionada
    RETURN
    MOVLW D'2'
    MOVWF N_TECLA     ; Tecla 2 detectada
    CALL TECL_DELAY
    RETURN

    CHECK_ROW_RB5
    BTFSS PORTB, RB5  ; Si RB5 = 0, tecla presionada
    RETURN
    MOVLW D'3'
    MOVWF N_TECLA     ; Tecla 3 detectada
    CALL TECL_DELAY
    RETURN

    CHECK_ROW_RB3_2
    BTFSS PORTB, RB3  ; Si RB3 = 0, tecla presionada
    RETURN
    MOVLW D'4'
    MOVWF N_TECLA     ; Tecla 4 detectada
    CALL TECL_DELAY
    RETURN

    CHECK_ROW_RB4_2
    BTFSS PORTB, RB4  ; Si RB4 = 0, tecla presionada
    RETURN
    MOVLW D'5'
    MOVWF N_TECLA     ; Tecla 5 detectada
    CALL TECL_DELAY
    RETURN

    CHECK_ROW_RB5_2
    BTFSS PORTB, RB5  ; Si RB5 = 0, tecla presionada
    RETURN
    MOVLW D'6'
    MOVWF N_TECLA     ; Tecla 6 detectada
    CALL TECL_DELAY
    RETURN

    TECL_RST
    MOVLW B'00000000'
    MOVWF N_TECLA
    MOVWF PORTB
    BCF INTCON,RBIF
    RETURN

    TECL_DELAY
    ; Simple delay para antirrebote (~20ms @ 4MHz)
    MOVLW D'100'
    MOVWF DIGIT_COUNTER
    DELAY_DEBOUNCE_LOOP
    NOP
    DECFSZ DIGIT_COUNTER,F
    GOTO DELAY_DEBOUNCE_LOOP
    RETURN

    TECL_LOAD
    ; Mapear numero de tecla a letra A-F y agregar al buffer
    CALL MAP_KEY_TO_LETTER
    CALL ADD_TO_BUFFER
    GOTO ISR_FIN

    ;====================================================================
    ; RUTINA DE MAPEO DE TECLAS A LETRAS
    ;====================================================================
    MAP_KEY_TO_LETTER
    ; N_TECLA contiene el numero de tecla (1-6)
    ; Devuelve el indice para la tabla (10-15 para A-F)
    MOVF N_TECLA,W
    SUBLW D'1'
    BTFSC STATUS,Z
    RETLW D'10'  ; Tecla 1 -> A (indice 10)
    MOVF N_TECLA,W
    SUBLW D'2'
    BTFSC STATUS,Z
    RETLW D'11'  ; Tecla 2 -> b (indice 11)
    MOVF N_TECLA,W
    SUBLW D'3'
    BTFSC STATUS,Z
    RETLW D'12'  ; Tecla 3 -> C (indice 12)
    MOVF N_TECLA,W
    SUBLW D'4'
    BTFSC STATUS,Z
    RETLW D'13'  ; Tecla 4 -> d (indice 13)
    MOVF N_TECLA,W
    SUBLW D'5'
    BTFSC STATUS,Z
    RETLW D'14'  ; Tecla 5 -> E (indice 14)
    MOVF N_TECLA,W
    SUBLW D'6'
    BTFSC STATUS,Z
    RETLW D'15'  ; Tecla 6 -> F (indice 15)
    RETLW D'16'  ; Valor por defecto (display vacio)

    ;====================================================================
    ; RUTINA DE BUFFER CIRCULAR
    ;====================================================================
    ADD_TO_BUFFER
    ; W contiene el indice de la tabla de displays
    MOVWF DSPL

    ; Guardar el valor en el buffer segun BUFFER_INDEX
    MOVF BUFFER_INDEX,W
    SUBLW D'0'
    BTFSC STATUS,Z
    GOTO STORE_BUFFER_1
    MOVF BUFFER_INDEX,W
    SUBLW D'1'
    BTFSC STATUS,Z
    GOTO STORE_BUFFER_2
    MOVF BUFFER_INDEX,W
    SUBLW D'2'
    BTFSC STATUS,Z
    GOTO STORE_BUFFER_3
    MOVF BUFFER_INDEX,W
    SUBLW D'3'
    BTFSC STATUS,Z
    GOTO STORE_BUFFER_4
    GOTO STORE_BUFFER_1  ; Si buffer_index > 3, volver al inicio

    STORE_BUFFER_1
    MOVF DSPL,W
    MOVWF DISPLAY_BUFFER_1
    GOTO INCREMENT_BUFFER_INDEX

    STORE_BUFFER_2
    MOVF DSPL,W
    MOVWF DISPLAY_BUFFER_2
    GOTO INCREMENT_BUFFER_INDEX

    STORE_BUFFER_3
    MOVF DSPL,W
    MOVWF DISPLAY_BUFFER_3
    GOTO INCREMENT_BUFFER_INDEX

    STORE_BUFFER_4
    MOVF DSPL,W
    MOVWF DISPLAY_BUFFER_4
    GOTO INCREMENT_BUFFER_INDEX

    INCREMENT_BUFFER_INDEX
    INCF BUFFER_INDEX,F
    MOVF BUFFER_INDEX,W
    SUBLW D'4'
    BTFSC STATUS,Z
    CLRF BUFFER_INDEX
    RETURN

    ISR_FIN
    SWAPF STATUS_TEMP,W
    MOVWF STATUS
    SWAPF W_TEMP,F
    SWAPF W_TEMP,W
    RETFIE


;====================================================================
      END



